export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'


export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'

export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS'
 

export const USER_DETAILS_REQUEST='USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS='USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILED='USER_DETAILS_FAILED'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_PROFILE_UPDATE_REQUEST='USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS='USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAILED='SER_PROFILE_UPDATE_FAILED'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'